<%@ page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>
<%@ page session="false"%>
<p class="text-left">團隊氣氛？</p>
<p class="text-left">同事們會分享、討論程式、互相幫忙嗎？</p>
<p class="text-left">是否會持續優化系統？</p>
<p class="text-left">開發流程？</p>
<p class="text-left">使用何種版控軟體？</p>
<p class="text-left">測試方式？</p>
<p class="text-left">部署方式？</p>
<p class="text-left">系統品質如何？</p>
<p class="text-left">有任何一種形式的 Code review 嗎？</p>
<p class="text-left">系統文件是以何種形態呈現？</p>
<p class="text-left">系統是外包的嗎？</p>
<p class="text-left">所有用到的 Framework 的版本概況？</p>
<p class="text-left">樣版是用 JSP 嗎？ 是否會用 Scriptlet 的風格寫商業邏輯？</p>
<p class="text-left">Web Container 用什麼？</p>
<p class="text-left">是否有機會參與需求討論、分析與規劃？</p>
<p class="text-left">未來系統的發展方向？</p>
<p class="text-left">管理專案/程式進度的人對於程式的掌握度？</p>
<p class="text-left">上班地點是這裡嗎？</p>
<p class="text-left">時段是 8:20 ~ 17:20？有彈性上下班嗎？</p>
<p class="text-left">工作上英文使用的比重大約為何？</p>
<p class="text-left">日常的工作內容會是如何？</p>
