<%@ page language="java" contentType="text/html; charset=utf-8" pageEncoding="utf-8"%>
<%@ page session="false"%>
	<p class="text-left">1. Do you agree to constantly improve existed system？</p>
    <!--p class="text-left">是否會持續優化系統？</p-->
    <p class="text-left">2. Do colleagues share thoughts or discuss code selflessly？</p>
    <!--p class="text-left">同事們會分享或討論程式嗎？</p-->
    <p class="text-left">3. How about the working environment and culture？</p>
    <!--p class="text-left">團隊氣氛？</p-->
    <p class="text-left">4. How about the development process？</p>
    <!--p class="text-left">開發流程？</p-->
    <p class="text-left">5. What kind of version control software your team use？</p>
    <!--p class="text-left">使用何種版控軟體？</p-->
    <p class="text-left">6. How do you test your program？</p>
    <!--p class="text-left">測試方式？</p-->
    <p class="text-left">7. How do you deploy system？</p>
    <!--p class="text-left">部署方式？</p-->
    <p class="text-left">8. Do you have any kind of Code review？</p>
    <!--p class="text-left">有任何一種形式的 Code review 嗎？</p-->
    <p class="text-left">9. Does the system is outsourcing？</p>
    <!--p class="text-left">系統是外包的嗎？</p-->
    <p class="text-left">10. What kind of framework your team use？</p>
    <!--p class="text-left">Framework 的版本概況？</p-->
    <p class="text-left">11. Does the system use JSP as template for view？</p>
    <p class="text-left">12. Does the JSP template be filled with Scriptlet to control business logic？</p>
    <!--p class="text-left">樣版是用 JSP 嗎？ 是否會用 Scriptlet 的風格寫商業邏輯？</p-->
    <p class="text-left">13. What kind of Web Container you use？</p>
    <!--p class="text-left">Web Container 用什麼？</p-->
    <p class="text-left">14. Can I have the chance to join the discussion of requirements, analysis and planning？</p>
    <!--p class="text-left">是否有機會參與需求討論、分析與規劃？</p-->
    <p class="text-left">15. Does the manager familiar with coding？</p>
    <!--p class="text-left">我的直屬主管對於程式的掌握度？</p-->
    <p class="text-left">16. What are goals of system in the future？</p>
    <!--p class="text-left">系統未來的方向？</p-->
    <p class="text-left">17. Working place and time？</p>
    <!--p class="text-left">上班地點與時段？</p-->
    <p class="text-left">18. Does the system have complete documents？</p>
    <!--p class="text-left">有系統文件嗎？</p-->
    <p class="text-left">19. How about the detail working content？</p>
    <!--p class="text-left">詳細工作內容？</p-->